[project]
name = "chainlit-agent-assignment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chainlit>=2.8.3",
    "load-dotenv>=0.1.0",
    "openai-agents>=0.3.3",
]

[project.scripts]
    chainlit-agent-assignment = "chainlit_agent_assignment:main"
    agnt = "chainlit_agent_assignment.agnt1:main"
 
chatbot = "agent_core:main"
[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
